"""add job extraction fields

Revision ID: 765a7fd2a9bf
Revises: 
Create Date: 2026-01-01 22:05:53.988403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '765a7fd2a9bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary_min', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('salary_max', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('salary_currency', sa.String(length=10), server_default='USD', nullable=True))
    op.add_column('jobs', sa.Column('salary_period', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('salary_raw', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('location_country', sa.String(length=10), nullable=True))
    op.add_column('jobs', sa.Column('location_city', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('seniority', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('preferred_skills', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('years_experience_min', sa.SmallInteger(), nullable=True))
    op.add_column('jobs', sa.Column('years_experience_max', sa.SmallInteger(), nullable=True))
    op.add_column('jobs', sa.Column('easy_apply', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('extracted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('extraction_confidence', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('scraped_text_debug', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('summary_generated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('embedding_id', sa.String(length=100), nullable=True))
    # Drop foreign key constraints first
    op.drop_constraint('saved_jobs_user_id_fkey', 'saved_jobs', type_='foreignkey')
    op.drop_constraint('fk_saved_jobs_job_id', 'saved_jobs', type_='foreignkey')
    op.drop_constraint('user_sessions_user_id_fkey', 'user_sessions', type_='foreignkey')
    op.drop_constraint('feature_access_user_id_fkey', 'feature_access', type_='foreignkey')
    
    # Skip UUID conversion for now - keep IDs as VARCHAR to preserve Clerk IDs
    # Update null values before making columns NOT NULL
    op.execute('UPDATE jobs SET updated_at = created_at WHERE updated_at IS NULL')
    op.execute('UPDATE jobs SET posting_date = created_at WHERE posting_date IS NULL')
    # Delete saved_jobs rows with null user_id
    op.execute('DELETE FROM saved_jobs WHERE user_id IS NULL')
    op.alter_column('jobs', 'required_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('jobs', 'company_logo_url',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('jobs', 'job_url',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('jobs', 'company_name',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('jobs', 'posting_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('jobs', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('jobs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('jobs', 'saved_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('ix_jobs_company_name', table_name='jobs')
    op.drop_constraint('jobs_job_url_key', 'jobs', type_='unique')
    op.drop_index('ix_jobs_job_url', table_name='jobs')
    op.create_index(op.f('ix_jobs_job_url'), 'jobs', ['job_url'], unique=True)
    op.drop_column('jobs', 'salary_range')
    op.drop_column('jobs', 'experience_level')
    op.drop_column('jobs', 'scraped_data')
    op.drop_column('jobs', 'job_description')
    op.alter_column('saved_jobs', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # Skip UUID conversion for job_id to keep it compatible with jobs.id
    op.alter_column('saved_jobs', 'reminder_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'priority_rank',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'rejection_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'interview_dates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'job_fit_score',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'targeted_resume_url',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'targeted_resume_drive_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'targeted_cover_letter_url',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'targeted_cover_letter_drive_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_saved_jobs_job_id'), 'saved_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_saved_jobs_user_id'), 'saved_jobs', ['user_id'], unique=False)
    # Recreate foreign key constraints
    op.create_foreign_key('fk_saved_jobs_job_id', 'saved_jobs', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('saved_jobs_user_id_fkey', 'saved_jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_sessions_user_id_fkey', 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('feature_access_user_id_fkey', 'feature_access', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('saved_jobs', 'scraped_data')
    op.drop_column('saved_jobs', 'job_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_jobs', sa.Column('job_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('saved_jobs', sa.Column('scraped_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'saved_jobs', type_='foreignkey')
    op.drop_constraint(None, 'saved_jobs', type_='foreignkey')
    op.create_foreign_key('fk_saved_jobs_job_id', 'saved_jobs', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key('saved_jobs_user_id_fkey', 'saved_jobs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_saved_jobs_user_id'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_job_id'), table_name='saved_jobs')
    op.alter_column('saved_jobs', 'targeted_cover_letter_drive_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'targeted_cover_letter_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'targeted_resume_drive_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'targeted_resume_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'job_fit_score',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'interview_dates',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'rejection_reason',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'priority_rank',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'reminder_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('saved_jobs', 'job_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('saved_jobs', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('jobs', sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('scraped_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('experience_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('salary_range', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_jobs_job_url'), table_name='jobs')
    op.create_index('ix_jobs_job_url', 'jobs', ['job_url'], unique=False)
    op.create_unique_constraint('jobs_job_url_key', 'jobs', ['job_url'])
    op.create_index('ix_jobs_company_name', 'jobs', ['company_name'], unique=False)
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('jobs', 'saved_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('jobs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('jobs', 'expiration_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('jobs', 'posting_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('jobs', 'company_logo_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('jobs', 'required_skills',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('jobs', 'job_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=False)
    op.alter_column('jobs', 'job_title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('jobs', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('jobs', 'embedding_id')
    op.drop_column('jobs', 'summary_generated_at')
    op.drop_column('jobs', 'summary')
    op.drop_column('jobs', 'scraped_text_debug')
    op.drop_column('jobs', 'extraction_confidence')
    op.drop_column('jobs', 'extracted_at')
    op.drop_column('jobs', 'easy_apply')
    op.drop_column('jobs', 'years_experience_max')
    op.drop_column('jobs', 'years_experience_min')
    op.drop_column('jobs', 'preferred_skills')
    op.drop_column('jobs', 'seniority')
    op.drop_column('jobs', 'location_city')
    op.drop_column('jobs', 'location_country')
    op.drop_column('jobs', 'salary_raw')
    op.drop_column('jobs', 'salary_period')
    op.drop_column('jobs', 'salary_currency')
    op.drop_column('jobs', 'salary_max')
    op.drop_column('jobs', 'salary_min')
    # ### end Alembic commands ###
